-- Day 2: move your clean_orders() SQL here.
--
-- Build clean_orders FROM orders_deduped:
--   * cast price text ("$1,209.50", "  42.99 ") to a number — strip $, comma, spaces
--   * cast quantity to an integer
--   * DROP rows missing a usable quantity or price
--   * normalize status: lower-case, trimmed, blanks -> 'unknown'
--   * parse order_date into a real DATE (Day 3: handle all three formats)
--   * add line_total = quantity * price
--
-- Until you fill this in, the file is a harmless placeholder.
SELECT 'TODO: clean_orders.sql not written yet' AS todo;
